version: '3.8'
services:

    #   PHP Server
    portfolio:
        build:
            args:
                user: naser
                uid: 1000
            context: ./ # path of Dockerfile
            dockerfile: Dockerfile

        image: portfolio
        container_name: portfolio
        restart: unless-stopped # automatically restarts the MySQL server if stops

        working_dir: /var/www # [/var/www] is the standard though you can use any name
        volumes:
            - ./:/var/www

        networks:
            - portfolio_network

    #   Database Server
    portfolio_db:
        image: mysql:8.0
        container_name: portfolio_db
        restart: unless-stopped # automatically restarts the MySQL server if stops

        ports:
            - "8098:3306" # custom_port_number : actual_port_number

        environment:
            MYSQL_DATABASE: ${DB_DATABASE} #database name
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} #database root password
            MYSQL_PASSWORD: ${DB_PASSWORD} #database password
            MYSQL_USER: ${DB_USERNAME} #database user
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

        volumes:
            - portfolio_data:/var/lib/mysql
        networks:
            - portfolio_network

    #   Nginx Server
    portfolio_nginx:
        image: nginx:latest
        container_name: portfolio_nginx
        restart: unless-stopped
        ports:
            - "9000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - portfolio_network

    #    phpmyadmin
    portfolio_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: portfolio_phpmyadmin
        restart: unless-stopped
        depends_on:
            - portfolio_db
        ports:
            - "9080:80"
        environment:
            PMA_HOST: portfolio_db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - portfolio_network

#   Docker Networks
networks:
    portfolio_network:
        driver: bridge

volumes:
    portfolio_data: ~
